sudo: required
language: generic
  8bca3592-d5dc-4715-b839-4cc543c0385b
services:
  - docker

before_install:
  - docker build -t srinurallapalli/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true srinurallapalli/react-test npm test

after_success:
  - docker build -t srinurallapalli/multi-client ./client
  - docker build -t srinurallapalli/multi-nginx ./nginx
  - docker build -t srinurallapalli/multi-server ./server
  - docker build -t srinurallapalli/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push srinurallapalli/multi-client
  - docker push srinurallapalli/multi-nginx
  - docker push srinurallapalli/multi-server
  - docker push srinurallapalli/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-267437562523"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
